### ISSUE TITLE
Imitation Learning Dataset Release Inquiry

### ISSUE THREAD

**Issue by www-Ye** [chernyadev/bigym#10]
Thank you for your interesting work! Will you be releasing your imitation learning datasets to the public?

**Comment by chernyadev** [comment]
Hello, thank you for your interest! You can download our latest dataset from the releases page: [https://github.com/chernyadev/bigym/releases/tag/v4.1.0](https://github.com/chernyadev/bigym/releases/tag/v4.1.0).

Currently, we are working on migrating from Google Cloud to GitHub Releases: [https://github.com/chernyadev/bigym/pull/8](https://github.com/chernyadev/bigym/pull/8). I recommend waiting for this change to be merged. However, you can already download the dataset manually and experiment with the demonstrations locally.

**Comment by www-Ye** [comment]
Thank you very much! I wish you all the best.
