### ISSUE TITLE
How can I use download the demonstration, do i need the authority to your bucket?

### ISSUE THREAD

**Issue by Harry-maximum** [chernyadev/bigym#11]

**Comment by Harry-maximum** [comment]
xxxxx@gmail.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).

**Comment by chernyadev** [comment]
Hello, thank you for your interest!

We are currently in the process of migration from Google Cloud, but you already can download dataset manually. Please refer to this issue: https://github.com/chernyadev/bigym/issues/10.

**Comment by Harry-maximum** [comment]
Thanks a lot, now I can already get the demonstration replayed.
