### ISSUE TITLE
No module named 'xr'

### ISSUE THREAD

**Issue by moojink** [chernyadev/bigym#12]
Hello,

Thank you for open-sourcing your work!

After installing the required pip packages, I am now trying to run the demo replay command shown in your README:
> python tools/demo_player/main.py

However, I run into an error about a missing `xr` package:
```
Traceback (most recent call last):
  File ".../bigym/tools/demo_player/main.py", line 4, in <module>
    from tools.demo_player.demo_player_window import DemoPlayerWindow
  File ".../bigym/tools/demo_player/demo_player_window.py", line 24, in <module>
    from tools.demo_player.demo_converter_window import DemoConverterWindow
  File ".../bigym/tools/demo_player/demo_converter_window.py", line 9, in <module>
    from tools.shared.utils import (
  File ".../bigym/tools/shared/utils.py", line 62, in <module>
    from vr.viewer.control_profiles.control_profile import ControlProfile
  File ".../bigym/vr/viewer/control_profiles/control_profile.py", line 7, in <module>
    from xr import Posef
ModuleNotFoundError: No module named 'xr'
```

Could you please tell me where I can download this missing package (and any other packages needed to run the commands in the README)? Thank you in advance!

-Moo Jin

**Comment by chernyadev** [comment]
Hello Moo, thank you for your interest!

Please also install the development dependencies:
```bash
pip install -e ".[dev]"
```

I'd also propose that you wait for this PR to be merged in: https://github.com/chernyadev/bigym/pull/8, as we are currently in the process of migrating from Google Cloud to GitHub releases. Once it's in, things will be much smoother.

Thank you!

**Comment by chernyadev** [comment]
Although you can currently download the dataset [here](https://github.com/chernyadev/bigym/releases/tag/v4.1.0), unzip it, and replay demonstrations locally using the demo player.

**Comment by moojink** [comment]
@chernyadev Thank you so much for your quick response!
