### ISSUE TITLE
Training and Evaluation code

### ISSUE THREAD

**Issue by jis3613** [chernyadev/bigym#14]
Hi, Thanks for providing wonderful work.
I want to run a RL or IL training code using BiGYM.
However, I could not find any training or evaluation code in the BiGYM repository.
Can you offer any tutorial code for training and evaluation ?
I would greatly appreciate it if you can provide any reference to utilize BiGYM benchmark to run any RL or IL algorithm.

Thank you!

**Comment by Yusufma03** [comment]
Hey, thanks for the interest in our work. We're working on releasing the training pipeline now. It will be release soon and we'll post updates. Please stay tuned!

**Comment by arthur801031** [comment]
Thank you for providing this awesome benchmark! Is the release of the training and evaluation code part of your roadmap?

**Comment by Yusufma03** [comment]
Hi @arthur801031, our training & eval code is available here: https://github.com/robobase-org/robobase. We will update our README to make it clearer soon.
