### ISSUE TITLE
Inquiry about VR Equipment

### ISSUE THREAD

**Issue by jkewang** [chernyadev/bigym#16]
Hello,
First of all, thank you for your excellent work! I have two questions that I would like to ask:

1. Are you using the original version of the Valve Index VR, or the newly released Valve Index VR V2?

2. Do you have any plans to publicly release the code for the reinforcement learning or imitation learning algorithms?

Thank you for your time and assistance!

**Comment by chernyadev** [comment]
Hello @jkewang,

Thank you for your kind words and interest in our work!

1. We used the 1st generation Valve Index VR for our project. However, the code should theoretically work with other SteamVR-based VR headsets on Ubuntu as well.
2. For integration with BiGym and other related code, please refer to this repository: [robobase-org/robobase](https://github.com/robobase-org/robobase). This repo includes support for reinforcement learning and imitation learning algorithms.

We hope this helps! Feel free to reach out if you have any more questions.
