### ISSUE TITLE
It's unsafe to rely on "mojo@dev" branch

### ISSUE THREAD

**Issue by jkewang** [chernyadev/bigym#20]
After a recent update in the mojo dev branch a few days ago, some parts of the code started to produce errors. 
Although temporarily changing the setup from 'git+https://git@github.com/stepjam/mojo.git@dev' to 'git+https://git@github.com/stepjam/mojo.git@main' can avoid this issue, future changes to the master might introduce new problems. It would be good to lock a specific tag to ensure code stability.

**Comment by chernyadev** [comment]
Hi, we are working on fixing this, will be closed in https://github.com/chernyadev/bigym/pull/19.

**Comment by chernyadev** [comment]
Closed with #19.
