### ISSUE TITLE
"envs/presets" Missing from package data

### ISSUE THREAD

**Issue by adrialopezescoriza** [chernyadev/bigym#21]
Hi,
Thank you for this very cool environment. I am trying out some humanoid manipulation tasks for a demo-assisted RL project I am working on. I ran into some issues when initializing the "PickBox", "StoreBox"... tasks. Basically, the envs/presets folder isn't in my pip installation. I believe that it is missing from the package data in setup.py? 

Thanks in advance.

**Comment by chernyadev** [comment]
Hi, thanks for spotting that! We’ll fix the `setup.py` as soon as possible.

**Comment by adrialopezescoriza** [comment]
Thanks!

**Comment by mxp1234** [comment]
i still encounterd the issue:"[Errno 2] No such file or directory: '/home/mxp/aloha-bigym/.venv/lib/python3.12/site-packages/bigym/envs/presets/cabinet_door.yaml'" ,there exist no folder "presets",how to fix it ?

**Comment by mxp1234** [comment]
> i still encounterd the issue:"[Errno 2] No such file or directory: '/home/mxp/aloha-bigym/.venv/lib/python3.12/site-packages/bigym/envs/presets/cabinet_door.yaml'" ,there exist no folder "presets",how to fix it ?
actually no problems here, i fix it
