### ISSUE TITLE
VR Docker Environment Cannot Detect VR Headset

### ISSUE THREAD

**Issue by helen9975** [chernyadev/bigym#29]
Thanks to the authors for open sourcing this! I have a question regarding setting up the vr headset.

When I followed the README for setting up docker, everything worked well. However, it seems that steam (within the container) cannot detect the VR devices that I have plugged into the machine.

Steps to reproduce: 
1. Follow https://github.com/chernyadev/bigym/tree/master/vr to set up vr
2. Launch steam

Here's what I see:
![image](https://github.com/user-attachments/assets/e3126894-4e16-442b-a7a5-6ea0fa047947)

Here's what I've tried:
- changing to the beta version
- fixing usb access permissions per https://github.com/chernyadev/bigym/issues/18

However, the issue persists.

Any help would be appreciated!

**Comment by nbackshall** [comment]
How are you plugging in the headset to the computer? What cables/ports are you using?

**Comment by chernyadev** [comment]
Also please, ensure that the headset is properly connected to the host machine. You can verify this by running the `lsusb` command in the terminal. The headset should appear in the command's output.

**Comment by helen9975** [comment]
Thanks! Fixed now :)
